version: '3'

services:

  app:
      build: ./docker/app/
      ports:
        - "${APP_PORT}:80"
        - "${SSL_PORT}:443"
      volumes:
        - .:/var/www/app
        - ./data/certbot/conf:/etc/letsencrypt
        - ./data/certbot/www:/var/www/certbot
      container_name: app  
      links:
        - database
        - redis
  certbot:
    image: certbot/certbot
    volumes:
      - .:/var/www/app
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    container_name: certbot   
    command: certonly --webroot --webroot-path=/var/www/app/public --email mahtonu@gmail.com --agree-tos --no-eff-email --force-renewal -d phpxperts.net -d www.phpxperts.net

  database:
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_DATABASE}"
    volumes:
      - ${BACKUP_PATH}/mysql:/var/lib/mysql
    ports:
      - ${DB_PORT_EXPOSE}:3306
    container_name: db

  redis:
    image: "redis:latest"
    volumes:
      - ${BACKUP_PATH}/redis:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT_EXPOSE}:6379
    container_name: redis
